create table if not exists public.rsvp (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  attendance text not null check (attendance in ('hadir', 'tidak-hadir', 'masih-ragu')),
  guests integer not null check (guests between 1 and 10),
  message text not null,
  created_at timestamp with time zone default now()
);

create index if not exists rsvp_created_at_idx on public.rsvp (created_at desc);
